name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5e06ef526975d2b3996c41cfd952cc671ca9fa950b7f25ad370b66c5233e90"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
