name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c00780cb36f340e7ade9a4d4c0569bebfd87614329ff25710118a46ba8ba63f5"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"
