name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e90079e61a3811b2013090f10389da38bee3328635ae6e2c33de9f440cd24811"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
