name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3455498bb919c4840ee238642f05eba1f8957011e9fa11307e0e733f061f138"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
