name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c888d44dee280a3d89d3c032a583324f6af71de7d4d31c3c2d4ebea0510eb847"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
