name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c7633921b99e5a2b42f823de9b518d96683455c7c477ffd06b0810e926c4934"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
