name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "103093f81b43fadeb910d3dce7c5312e8bcd91237dba5722df762eb2e1d8b286"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
