name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee7895b12311a7eb6e104625fa2c44b2343ca6a3110676213c1753cfd6647ae"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
