name = "MTR Beta Testing"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb5400bf867b503534f37de850c3a0a6a0ec8db90c47f8fddaa5cdc81d63bf9f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
